name: CD

on:
  workflow_run:
    workflows: ['CI']
    types: [completed]
    branches: [main]

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # TODO: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO: Log in to Azure Container Registry
      # Hint: uses docker/login-action@v3
      # needs: registry, username, password — all from secrets
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # TODO: Build the Docker image
      # Hint: use "docker build" with a -t flag
      # Tag it as: ${{ secrets.ACR_LOGIN_SERVER }}/pokedex:latest
      - name: Build docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/pokedex:latest \
            -t ${{ secrets.ACR_LOGIN_SERVER }}/pokedex:${{ github.event.workflow_run.head_sha }} \
            .

      # TODO: Push the image
      # Hint: use "docker push" with the full image name
      - name: Push docker image
        run: docker push --all-tags ${{ secrets.ACR_LOGIN_SERVER }}/pokedex

      # TODO: Log in to Azure using the service principal credentials
      # Hint: uses azure/login@v2
      # needs: creds — from which secret?
      - name: Login to azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # TODO: Tell Azure Container Apps to redeploy with the new image
      # Hint: use "run:" with the az containerapp update command
      # Use ${{ secrets.ACR_LOGIN_SERVER }} instead of hardcoding the registry URL
      - name: Redeploy to ACR with updated image
        run: |
          az containerapp update \
            --name pokedex \
            --resource-group rg-pokedex-syafiq \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/pokedex:${{ github.event.workflow_run.head_sha }}
